version: '3'
services:
  frontend:
    container_name: mynginx
    image: mynginx
    build: 
      context: .
      dockerfile: ./front_dir/Dockerfile.dev
    networks:
      lan_front:
         ipv4_address: 192.168.56.10
    ports:
      - "8081:80"
    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqlbase
    image: mysqlbase
    build:
      context: .
      dockerfile: ./db_dir/Dockerfile.dev
    networks:
      lan_back:
         ipv4_address: 192.168.56.1
networks:
  lan_front:
    driver: bridge
    ipam:
       driver: default
  lan_back:
    driver: bridge
    ipam:
       driver: default

  